name: jami-store-requests-manager
run-name: ${{ github.actor }} requests attention
on:
  issue_comment:
    types: [created, edited]
jobs:
  verify-csr:
    runs-on:  ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'new organization request') && contains(github.event.comment.body, '/csr')
    steps:
      - name: verify the CSR file is attached
        id: verify_attached_csr
        uses: actions/github-script@v6
        with:
          script: |
            const regex = /^https:\/\/github\.com\/savoirfairelinux\/jami-plugins-store-requests\/files\/.*/;
            return regex.match(github.event.comment.body);
      - name: ask to upload the CSR file
        if: steps.verify_attached_csr.outputs.result.length == 0
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Please upload the CSR file'
            })
            exit 1
      - name: add label to process the request
        if: steps.verify_attached_csr.outputs.result.length == 1
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'CSR file uploaded, verification in progress'
            })
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['csr verification in progress']
            })
      - name: request verify the csr
        id: request-verify-csr
        if: steps.verify_attached_csr.outputs.result.length == 1
        uses: actions/github-script@v6
        with:
          script: curl -s ${{ steps.verify_attached_csr.outputs.result[0] }} | tar -xz -O csr.pem | openssl req -noout -text
      - name: handle error
        if: ! contains(steps.request-verify-csr.outputs, 'OK')
        id: request-verify-csr-error
        run: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'CSR is invalid, Please retry'
            })
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['invalid csr']
            })
      - name: handle success when requesting verify the csr
        if: contains(steps.request-verify-csr.outputs, 'OK') && steps.verify_attached_csr.outputs.result.length == 1
        run: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{ github.actor}}, your certificate signing request is valid. Please wait for a store manager to process your request.'
          })
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['valid csr']
          })
          github.rest.issues.removeLabel({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: 'invalid csr'
          })
      - name: remove label to process the request
        if: steps.verify_attached_csr.outputs.result.length == 1
        run: |
          github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'verification in progress'
            })
